---
- hosts: junos
  tasks:
  - name: Deploy configs
    napalm_install_config:
        provider: "{{napalm_provider}}"
        config_file: "configs/{{inventory_hostname}}.conf"
        commit_changes: True
        get_diffs: True
        replace_config: True
