---
- name: Validate VPNv4 Service
  hosts: all
  roles:
   - Juniper.junos
  #  vars:
  #   target_service: all
  tasks:
    - block:
        - set_fact:
            vpnv4_services: "{{lookup('file', '../services-vpnv4.yml') | from_yaml }}"
      delegate_to: localhost
      run_once: true
    - include_tasks: "../getters/get-interfaces-config.yml"
    - set_fact:
       interfaces: "{{lookup('file', '../outputs/{{inventory_hostname}}-interfaces-config.yml') | from_yaml }}"
    - set_fact:
       router_vpnv4_interfaces: "{{ vpnv4_services | vpn4_interfaces  }}"
    - assert:
       that: "item in interfaces"
       msg: "Service interface not present in the router configuration."
      loop: "{{router_vpnv4_interfaces[inventory_hostname]}}"
      when: inventory_hostname in router_vpnv4_interfaces
